server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Tasks
          uri: http://localhost:8001/
          predicates:
            - Path=/tasks/**